### ISSUE TITLE
2.0.8 will cause network crashes in system apps

### ISSUE THREAD

**Issue by KleinerSource** [opa334/Dopamine#460]
device  iphonex  16.1.2

The issue with the 2.0.8 VPN has been resolved, but it can cause the system's APP network to crash. For example, Homekit did not respond and phone transfer failed. Restarting the user space can recover, but the problem will reappear shortly thereafter

2.0.6 VPN has a problem of not being able to start, but before restarting the user space, disable some plugins. After restarting the user space, if the VPN becomes available, enable all plugins. VPN can continue to work normally unless the user space is restarted But there won't be any issues with system app network crashes

**Comment by opa334** [comment]
> 2.0.6 VPN has a problem of not being able to start, but before restarting the user space, disable some plugins. After restarting the user space, if the VPN becomes available, enable all plugins. VPN can continue to work normally unless the user space is restarted But there won't be any issues with system app network crashes

That's the worst solution ever, do not do this.

Besides, if something crashes then attach a crashlog from KrashKop?...

**Comment by KleinerSource** [comment]
> > 2.0.6 VPN has a problem of not being able to start, but before restarting the user space, disable some plugins. After restarting the user space, if the VPN becomes available, enable all plugins. VPN can continue to work normally unless the user space is restarted But there won't be any issues with system app network crashes
> 
> That's the worst solution ever, do not do this.
> 
> Besides, if something crashes then attach a crashlog from KrashKop?...

Incident Identifier: 3A54BA93-4046-4D13-9520-BD19BB4EF439
CrashReporter Key:   6b717b07bdb588a900459c2079de978b4241f9df
Hardware Model:      iPhone10,3
Process:             terminusd [26484]
Path:                /usr/libexec/terminusd
Identifier:          terminusd
Version:             ???
Code Type:           ARM-64 (Native)
Role:                Unspecified
Parent Process:      launchd [1]
Coalition:           com.apple.terminusd [3937]

Date/Time:           2024-02-29 21:22:19.4776 +0800
Launch Time:         2024-02-29 21:22:19.1237 +0800
OS Version:          iPhone OS 16.1.2 (20B110)
Release Type:        User
Baseband Version:    8.04.01
Report Version:      104

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000001ef5f2fcc
Termination Reason: SIGNAL 5 Trace/BPT trap: 5
Terminating Process: exc handler [26484]

Triggered by Thread:  1

Thread 0:
0   libsystem_kernel.dylib        	       0x1e32b9cd4 __semwait_signal_nocancel + 8
1   libsystem_c.dylib             	       0x1b161cf70 nanosleep$NOCANCEL + 212
2   libsystem_c.dylib             	       0x1b161a404 sleep$NOCANCEL + 48
3   libdispatch.dylib             	       0x1b15c07f0 _dispatch_queue_cleanup2 + 204
4   libsystem_pthread.dylib       	       0x1f205cb18 _pthread_tsd_cleanup + 616
5   libsystem_pthread.dylib       	       0x1f205f9c8 _pthread_exit + 80
6   libsystem_pthread.dylib       	       0x1f205de30 pthread_exit + 56
7   libdispatch.dylib             	       0x1b15bc224 dispatch_main$VARIANT$armv81 + 120
8   terminusd                     	       0x100b4ab18 0x100a80000 + 830232
9   dyld                          	       0x100e57df0 start + 2096

Thread 1 name:   Dispatch queue: terminusd.main.root
Thread 1 Crashed:
0   NetworkRelay                  	       0x1ef5f2fcc _NRLogAbortWithPack + 64
1   NetworkRelay                  	       0x1ef5f2fc4 _NRLogAbortWithPack + 56
2   terminusd                     	       0x100b30e08 0x100a80000 [+ 724488](tel:+ 724488)
3   terminusd                     	       0x100b30c1c 0x100a80000 [+ 723996](tel:+ 723996)
4   libdispatch.dylib             	       0x1b15da7c8 _dispatch_client_callout + 16
5   libdispatch.dylib             	       0x1b15aaf40 _dispatch_once_callout + 28
6   terminusd                     	       0x100aefdec 0x100a80000 + 458220
7   terminusd                     	       0x100aef204 0x100a80000 + 455172
8   terminusd                     	       0x100aef0a4 0x100a80000 + 454820
9   libdispatch.dylib             	       0x1b15da7c8 _dispatch_client_callout + 16
10  libdispatch.dylib             	       0x1b15aaf40 _dispatch_once_callout + 28
11  terminusd                     	       0x100b4b2fc 0x100a80000 + 832252
12  libdispatch.dylib             	       0x1b15d9850 _dispatch_call_block_and_release + 24
13  libdispatch.dylib             	       0x1b15da7c8 _dispatch_client_callout + 16
14  libdispatch.dylib             	       0x1b15b5854 _dispatch_lane_serial_drain$VARIANT$armv81 + 604
15  libdispatch.dylib             	       0x1b15b6318 _dispatch_lane_invoke$VARIANT$armv81 + 432
16  libdispatch.dylib             	       0x1b15bed48 _dispatch_root_queue_drain + 328
17  libdispatch.dylib             	       0x1b15beb1c _dispatch_worker_thread + 248
18  libsystem_pthread.dylib       	       0x1f205c060 _pthread_start + 116
19  libsystem_pthread.dylib       	       0x1f205a688 thread_start + 8

Thread 2:
0   libsystem_kernel.dylib        	       0x1e32b9a94 __sigsuspend_nocancel + 8
1   libdispatch.dylib             	       0x1b15c08e0 _dispatch_sigsuspend + 44
2   libdispatch.dylib             	       0x1b15c08b4 _dispatch_sig_thread + 56

Thread 3:
0   libsystem_pthread.dylib       	       0x1f205a674 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x1f205a674 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x1f205a674 start_wqthread + 0


Thread 1 crashed with ARM Thread State (64-bit):
    x0: 0x000000055cb06ff0   x1: 0x00000001a63827fa   x2: 0x00000002062cd5e8   x3: 0x000000055ca19527
    x4: 0xfffffffba417c3ae   x5: 0x000000000000000a   x6: 0x0000000000000004   x7: 0x0000000000000027
    x8: 0x0000000203445000   x9: 0x000000007fffffff  x10: 0x0000000209a89158  x11: 0x00ed000209a89159
   x12: 0x0000000000249f00  x13: 0x6e6f697373655379  x14: 0x00000002062cd5e8  x15: 0x00000002062cd5e8
   x16: 0x00000001b15a967c  x17: 0x00000001b15d9d58  x18: 0x0000000000000000  x19: 0x000000055ca194f0
   x20: 0x000000055cb06ff0  x21: 0x0000000100b7da96  x22: 0x0000000100bb5000  x23: 0x0000000100bb9000
   x24: 0x0000000000000000  x25: 0x0000000100bb4000  x26: 0x0000000100b845be  x27: 0x0000000100b845c1
   x28: 0x00000002034454e9   fp: 0x000000016f406a10   lr: 0x00000001ef5f2fc4
    sp: 0x000000016f406a00   pc: 0x00000001ef5f2fcc cpsr: 0x60000000
   far: 0x0000000100b958ba  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x1e32b1000 -        0x1e32e6fef libsystem_kernel.dylib arm64  <7798d964d97e320b99a295b63e0f882b> /usr/lib/system/libsystem_kernel.dylib
       0x1b15fa000 -        0x1b1675ff7 libsystem_c.dylib arm64  <b9a8f342bc2f3c16afff1f78b98d815e> /usr/lib/system/libsystem_c.dylib
       0x1b1576000 -        0x1b15f9fff libdispatch.dylib arm64  <19f4cd59ab923ed49730174fa4b1468e> /usr/lib/system/libdispatch.dylib
       0x1f2059000 -        0x1f2069fff libsystem_pthread.dylib arm64  <0f4eb3635df330d495d23ada3d3e82f2> /usr/lib/system/libsystem_pthread.dylib
       0x100a80000 -        0x100b97fff terminusd arm64  <06359c3d0b293d5da4506993b37fea7f> /usr/libexec/terminusd
       0x100e44000 -        0x100ebffff dyld arm64  <444f50414d494e45444f50414d494e45> /usr/lib/dyld
       0x1ef5e9000 -        0x1ef643fff NetworkRelay arm64  <75db3b40b2c33f1eb95aae0109dd4219> /System/Library/PrivateFrameworks/NetworkRelay.framework/NetworkRelay

Error Formulating Crash Report:
dyld_process_snapshot_create_for_process failed with 5

EOF

**Comment by opa334** [comment]
Please try again in 2.0.9. terminusd crashes should be fixed now.

**Comment by KleinerSource** [comment]
> Please try again in 2.0.9. terminusd crashes should be fixed now.

Unfortunately, the 2.0.9 terminal still crashes


Incident Identifier: B591676D-7697-4958-B41C-B12B908CEF74
CrashReporter Key:   6b717b07bdb588a900459c2079de978b4241f9df
Hardware Model:      iPhone10,3
Process:             terminusd [32834]
Path:                /usr/libexec/terminusd
Identifier:          terminusd
Version:             ???
Code Type:           ARM-64 (Native)
Role:                Unspecified
Parent Process:      launchd [1]
Coalition:           com.apple.terminusd [4896]

Date/Time:           2024-03-01 08:08:18.8687 +0800
Launch Time:         2024-03-01 08:08:18.7150 +0800
OS Version:          iPhone OS 16.1.2 (20B110)
Release Type:        User
Baseband Version:    8.04.01
Report Version:      104

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000001ef5f2fcc
Termination Reason: SIGNAL 5 Trace/BPT trap: 5
Terminating Process: exc handler [32834]

Triggered by Thread:  1

Thread 0:
0   libsystem_kernel.dylib        	       0x1e32b9cd4 __semwait_signal_nocancel + 8
1   libsystem_c.dylib             	       0x1b161cf70 nanosleep$NOCANCEL + 212
2   libsystem_c.dylib             	       0x1b161a404 sleep$NOCANCEL + 48
3   libdispatch.dylib             	       0x1b15c07f0 _dispatch_queue_cleanup2 + 204
4   libsystem_pthread.dylib       	       0x1f205cb18 _pthread_tsd_cleanup + 616
5   libsystem_pthread.dylib       	       0x1f205f9c8 _pthread_exit + 80
6   libsystem_pthread.dylib       	       0x1f205de30 pthread_exit + 56
7   libdispatch.dylib             	       0x1b15bc224 dispatch_main$VARIANT$armv81 + 120
8   terminusd                     	       0x1040dab18 0x104010000 + 830232
9   dyld                          	       0x1044b3df0 start + 2096

Thread 1 name:   Dispatch queue: terminusd.main.root
Thread 1 Crashed:
0   NetworkRelay                  	       0x1ef5f2fcc _NRLogAbortWithPack + 64
1   NetworkRelay                  	       0x1ef5f2fc4 _NRLogAbortWithPack + 56
2   terminusd                     	       0x1040c0e08 0x104010000 + 724488
3   terminusd                     	       0x1040c0c1c 0x104010000 + 723996
4   libdispatch.dylib             	       0x1b15da7c8 _dispatch_client_callout + 16
5   libdispatch.dylib             	       0x1b15aaf40 _dispatch_once_callout + 28
6   terminusd                     	       0x10407fdec 0x104010000 + 458220
7   terminusd                     	       0x10407f204 0x104010000 + 455172
8   terminusd                     	       0x10407f0a4 0x104010000 + 454820
9   libdispatch.dylib             	       0x1b15da7c8 _dispatch_client_callout + 16
10  libdispatch.dylib             	       0x1b15aaf40 _dispatch_once_callout + 28
11  terminusd                     	       0x1040db2fc 0x104010000 + 832252
12  libdispatch.dylib             	       0x1b15d9850 _dispatch_call_block_and_release + 24
13  libdispatch.dylib             	       0x1b15da7c8 _dispatch_client_callout + 16
14  libdispatch.dylib             	       0x1b15b5854 _dispatch_lane_serial_drain$VARIANT$armv81 + 604
15  libdispatch.dylib             	       0x1b15b6318 _dispatch_lane_invoke$VARIANT$armv81 + 432
16  libdispatch.dylib             	       0x1b15bed48 _dispatch_root_queue_drain + 328
17  libdispatch.dylib             	       0x1b15beb1c _dispatch_worker_thread + 248
18  libsystem_pthread.dylib       	       0x1f205c060 _pthread_start + 116
19  libsystem_pthread.dylib       	       0x1f205a688 thread_start + 8

Thread 2:
0   libsystem_kernel.dylib        	       0x1e32b9a94 __sigsuspend_nocancel + 8
1   libdispatch.dylib             	       0x1b15c08e0 _dispatch_sigsuspend + 44
2   libdispatch.dylib             	       0x1b15c08b4 _dispatch_sig_thread + 56

Thread 3:
0   libsystem_pthread.dylib       	       0x1f205a674 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x1f205a674 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x1f205a674 start_wqthread + 0


Thread 1 crashed with ARM Thread State (64-bit):
    x0: 0x0000000ba6907360   x1: 0x00000001a63827fa   x2: 0x00000002062cd5e8   x3: 0x0000000ba6908c47
    x4: 0xfffffff55d81cc8e   x5: 0x000000000000000a   x6: 0x000000000000005d   x7: 0x0000000000000027
    x8: 0x0000000203445000   x9: 0x000000007fffffff  x10: 0x0000000209a89158  x11: 0x00ed000209a89159
   x12: 0x0000000000249f00  x13: 0x6e6f697373655379  x14: 0x00000002062cd5e8  x15: 0x00000002062cd5e8
   x16: 0x00000001b15a967c  x17: 0x00000001b15d9d58  x18: 0x0000000000000000  x19: 0x0000000ba6908c10
   x20: 0x0000000ba6907360  x21: 0x000000010410da96  x22: 0x0000000104145000  x23: 0x0000000104149000
   x24: 0x0000000000000000  x25: 0x0000000104144000  x26: 0x00000001041145be  x27: 0x00000001041145c1
   x28: 0x00000002034454e9   fp: 0x000000016be76a10   lr: 0x00000001ef5f2fc4
    sp: 0x000000016be76a00   pc: 0x00000001ef5f2fcc cpsr: 0x60000000
   far: 0x00000001041258ba  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x1e32b1000 -        0x1e32e6fef libsystem_kernel.dylib arm64  <7798d964d97e320b99a295b63e0f882b> /usr/lib/system/libsystem_kernel.dylib
       0x1b15fa000 -        0x1b1675ff7 libsystem_c.dylib arm64  <b9a8f342bc2f3c16afff1f78b98d815e> /usr/lib/system/libsystem_c.dylib
       0x1b1576000 -        0x1b15f9fff libdispatch.dylib arm64  <19f4cd59ab923ed49730174fa4b1468e> /usr/lib/system/libdispatch.dylib
       0x1f2059000 -        0x1f2069fff libsystem_pthread.dylib arm64  <0f4eb3635df330d495d23ada3d3e82f2> /usr/lib/system/libsystem_pthread.dylib
       0x104010000 -        0x104127fff terminusd arm64  <06359c3d0b293d5da4506993b37fea7f> /usr/libexec/terminusd
       0x1044a0000 -        0x10451bfff dyld arm64  <444f50414d494e45444f50414d494e45> /usr/lib/dyld
       0x1ef5e9000 -        0x1ef643fff NetworkRelay arm64  <75db3b40b2c33f1eb95aae0109dd4219> /System/Library/PrivateFrameworks/NetworkRelay.framework/NetworkRelay

EOF

**Comment by opa334** [comment]
weird, did you OTA update? does it still happen after reboot + rejb?

**Comment by KleinerSource** [comment]
I'm not sure if OTA will be upgraded after too long I restarted my device and jailbroken terminusd, but it also crashed. But from 2.0.3 to 2.0.6, I have never experienced a crash when using terminusd for a long time

**Comment by opa334** [comment]
This should be actually fixed now in latest nightly, please test.

https://nightly.link/opa334/Dopamine/actions/runs/8165294582/Dopamine.zip

**Comment by opa334** [comment]
Fixed in 2.0.10+
